export const searchCopy = {
  id: {
    filtersHeading: "Filter",
    priceHeading: "Rentang harga",
    minPriceLabel: "Harga minimum",
    maxPriceLabel: "Harga maksimum",
    minPricePlaceholder: "Rp 0",
    maxPricePlaceholder: "Tanpa batas",
    amenitiesHeading: "Fasilitas",
    statusHeading: "Ketersediaan",
    availableOnly: "Masih ada kamar kosong",
    verifiedOnly: "Hanya kos terverifikasi",
    clearFilters: "Hapus semua filter",
    resultsHeading: "Hasil pencarian",
    noMatchHint: "Tidak ada hasil dengan filter ini",
  },
  en: {
    filtersHeading: "Filters",
    priceHeading: "Price range",
    minPriceLabel: "Minimum price",
    maxPriceLabel: "Maximum price",
    minPricePlaceholder: "IDR 0",
    maxPricePlaceholder: "No limit",
    amenitiesHeading: "Amenities",
    statusHeading: "Availability",
    availableOnly: "Has rooms available",
    verifiedOnly: "Verified kos only",
    clearFilters: "Clear all filters",
    resultsHeading: "Search results",
    noMatchHint: "No results with these filters",
  },
} as const;
