export const ownerCopy = {
  id: {
    area: "Area pemilik",
    dashboard: "Dasbor",
    listings: "Kos saya",
    requests: "Permintaan sewa",
    questions: "Tanya jawab",

    dashboardTitle: "Dasbor pemilik",
    dashboardBody: "Ringkasan yang perlu kamu tindak lanjuti hari ini.",
    statPendingRequests: "Permintaan menunggu",
    statUnanswered: "Pertanyaan belum dijawab",
    statPublished: "Kos tayang",
    statTotalListings: "Total kos",
    reviewRequests: "Tinjau permintaan",
    answerQuestions: "Jawab pertanyaan",
    manageListings: "Kelola kos",
    allClear: "Tidak ada yang perlu ditindak lanjuti.",

    listingsTitle: "Kos saya",
    listingsBody:
      "Atur kos mana yang tayang untuk pencari. Penyuntingan detail hadir bersama API.",
    published: "Tayang",
    unpublished: "Tidak tayang",
    suspended: "Ditangguhkan admin",
    publish: "Tayangkan",
    unpublish: "Sembunyikan",
    roomsAvailable: "kamar tersedia",
    fullyBooked: "Penuh",
    publishedToast: "Kos ditayangkan.",
    unpublishedToast: "Kos disembunyikan dari pencarian.",
    suspendedHint: "Hanya admin yang dapat mencabut penangguhan.",

    requestsTitle: "Permintaan sewa masuk",
    requestsBody:
      "Setujui atau tolak pengajuan penyewa. Tidak ada pembayaran yang diproses.",
    requestsEmpty: "Belum ada permintaan sewa yang masuk.",
    approve: "Setujui",
    reject: "Tolak",
    approvedToast: "Permintaan disetujui.",
    rejectedToast: "Permintaan ditolak.",
    filterAll: "Semua",
    decidedAlready: "Sudah diputuskan",

    questionsTitle: "Pertanyaan penyewa",
    questionsBody:
      "Jawab secara asinkron. Jawaban yang terkirim tampil di halaman kos.",
    questionsEmpty: "Belum ada pertanyaan dari penyewa.",
    answerPlaceholder: "Tulis jawaban untuk penyewa…",
    sendAnswer: "Kirim jawaban",
    answeredToast: "Jawaban terkirim.",
    yourAnswer: "Jawabanmu",
    askedOn: "Ditanya",
  },
  en: {
    area: "Owner area",
    dashboard: "Dashboard",
    listings: "My kos",
    requests: "Rental requests",
    questions: "Questions",

    dashboardTitle: "Owner dashboard",
    dashboardBody: "What needs your attention today.",
    statPendingRequests: "Pending requests",
    statUnanswered: "Unanswered questions",
    statPublished: "Live kos",
    statTotalListings: "Total kos",
    reviewRequests: "Review requests",
    answerQuestions: "Answer questions",
    manageListings: "Manage kos",
    allClear: "Nothing needs your attention.",

    listingsTitle: "My kos",
    listingsBody:
      "Choose which kos renters can see. Detail editing arrives with the API.",
    published: "Live",
    unpublished: "Hidden",
    suspended: "Suspended by admin",
    publish: "Publish",
    unpublish: "Hide",
    roomsAvailable: "rooms available",
    fullyBooked: "Full",
    publishedToast: "Kos published.",
    unpublishedToast: "Kos hidden from search.",
    suspendedHint: "Only an administrator can lift a suspension.",

    requestsTitle: "Incoming rental requests",
    requestsBody:
      "Approve or reject renter requests. No payment is processed.",
    requestsEmpty: "No rental requests yet.",
    approve: "Approve",
    reject: "Reject",
    approvedToast: "Request approved.",
    rejectedToast: "Request rejected.",
    filterAll: "All",
    decidedAlready: "Already decided",

    questionsTitle: "Renter questions",
    questionsBody:
      "Answer asynchronously. Sent answers appear on the kos page.",
    questionsEmpty: "No renter questions yet.",
    answerPlaceholder: "Write an answer for the renter…",
    sendAnswer: "Send answer",
    answeredToast: "Answer sent.",
    yourAnswer: "Your answer",
    askedOn: "Asked",
  },
} as const;
