export const ownerCopy = {
  id: {
    area: "Area pemilik",
    dashboard: "Dasbor",
    listings: "Kos saya",
    requests: "Permintaan sewa",
    questions: "Tanya jawab",

    dashboardTitle: "Dasbor pemilik",
    dashboardBody: "Ringkasan yang perlu kamu tindak lanjuti hari ini.",
    statPendingRequests: "Permintaan menunggu",
    statUnanswered: "Pertanyaan belum dijawab",
    statPublished: "Kos tayang",
    statTotalListings: "Total kos",
    reviewRequests: "Tinjau permintaan",
    answerQuestions: "Jawab pertanyaan",
    manageListings: "Kelola kos",
    allClear: "Tidak ada yang perlu ditindak lanjuti.",

    sectionEarnings: "Pendapatan bulan ini",
    sectionOccupancy: "Hunian",
    sectionDemand: "Permintaan bulan ini",
    sectionTasks: "Perlu ditindak lanjuti",
    earningsGross: "Pendapatan kotor",
    earningsCommission: "Komisi Papikos",
    earningsNet: "Diterima pemilik",
    earningsFrom: "dari {count} permintaan disetujui",
    earningsNote:
      "Dihitung dari permintaan yang kamu setujui dan harga yang kamu pasang. Papikos tidak menerima atau menyimpan uang; pembayaran tetap langsung dengan penyewa.",
    occupancyRate: "Tingkat hunian",
    occupancyRooms: "kamar terisi",
    occupancyFree: "Kamar kosong",
    demandTotal: "Total permintaan",
    demandApproved: "Disetujui",
    demandRejected: "Ditolak",
    approvalRate: "Tingkat persetujuan",
    noDecisions: "Belum ada keputusan",
    fullyBookedAlert: "kos sudah penuh",

    listingsTitle: "Kos saya",
    listingsBody:
      "Atur kos mana yang tayang untuk pencari. Penyuntingan detail hadir bersama API.",
    published: "Tayang",
    unpublished: "Tidak tayang",
    suspended: "Ditangguhkan admin",
    publish: "Tayangkan",
    unpublish: "Sembunyikan",
    roomsAvailable: "kamar tersedia",
    fullyBooked: "Penuh",
    publishedToast: "Kos ditayangkan.",
    unpublishedToast: "Kos disembunyikan dari pencarian.",
    suspendedHint: "Hanya admin yang dapat mencabut penangguhan.",
    edit: "Ubah",

    editTitle: "Ubah detail kos",
    editBody: "Perubahan langsung tampil untuk pencari kos.",
    basics: "Informasi dasar",
    fieldName: "Nama kos",
    fieldDistrict: "Kecamatan",
    fieldType: "Tipe kos",
    fieldDescription: "Deskripsi",
    fieldPrice: "Harga bulanan",
    fieldPromo: "Harga promo",
    promoHint: "Kosongkan bila tidak ada diskon.",
    promoInvalid: "Harga promo harus lebih murah dari harga normal.",
    roomsSection: "Kamar",
    roomPrice: "Harga",
    roomAvailable: "Kamar kosong",
    photosSection: "Foto kos",
    photosBody:
      "Foto pertama dipakai sebagai sampul. Maksimal {max} foto; gambar dikecilkan otomatis agar muat di penyimpanan browser.",
    photosAdd: "Tambah foto",
    photosEmpty: "Belum ada foto. Kos memakai ilustrasi bawaan.",
    photosCount: "{count} dari {max} foto · {size}",
    photoCover: "Sampul",
    photoMakeCover: "Jadikan sampul",
    photoRemove: "Hapus foto",
    photoErrorType: "Hanya berkas gambar yang bisa diunggah.",
    photoErrorCap: "Batas {max} foto tercapai, sisanya tidak diunggah.",
    photoErrorRead: "Gambar tidak bisa dibaca. Coba berkas lain.",
    photoErrorQuota:
      "Penyimpanan browser penuh. Hapus sebagian foto lalu simpan lagi.",
    photosUploading: "Memproses foto…",
    amenitiesSection: "Fasilitas",
    rulesSection: "Peraturan",
    ruleAllowed: "Diizinkan",
    rulesStandard: "Peraturan umum",
    rulesCustom: "Peraturan tambahan",
    rulesCustomBody:
      "Peraturan umum tetap berlaku. Tambahkan aturan khusus kosmu di sini.",
    ruleNewPlaceholder: "Contoh: Jam tamu maksimal pukul 21.00",
    ruleAdd: "Tambah peraturan",
    ruleDelete: "Hapus peraturan",
    ruleAllowedToggle: "Diizinkan",
    ruleForbiddenToggle: "Tidak diizinkan",
    ruleEmptyError: "Tulis dulu isi peraturannya.",
    costsSection: "Rincian biaya",
    costIncluded: "Termasuk harga",
    costAmount: "Nominal",
    save: "Simpan perubahan",
    saved: "Perubahan tersimpan.",
    reset: "Kembalikan ke data awal",
    resetDone: "Perubahan dikembalikan.",
    edited: "Diubah pemilik",
    backToListings: "Kembali ke daftar kos",

    requestsTitle: "Permintaan sewa masuk",
    requestsBody:
      "Setujui atau tolak pengajuan penyewa. Tidak ada pembayaran yang diproses.",
    requestsEmpty: "Belum ada permintaan sewa yang masuk.",
    approve: "Setujui",
    reject: "Tolak",
    approvedToast: "Permintaan disetujui.",
    rejectedToast: "Permintaan ditolak.",
    filterAll: "Semua",
    decidedAlready: "Sudah diputuskan",

    questionsTitle: "Pertanyaan penyewa",
    questionsBody:
      "Jawab secara asinkron. Jawaban yang terkirim tampil di halaman kos.",
    questionsEmpty: "Belum ada pertanyaan dari penyewa.",
    answerPlaceholder: "Tulis jawaban untuk penyewa…",
    sendAnswer: "Kirim jawaban",
    answeredToast: "Jawaban terkirim.",
    yourAnswer: "Jawabanmu",
    askedOn: "Ditanya",
  },
  en: {
    area: "Owner area",
    dashboard: "Dashboard",
    listings: "My kos",
    requests: "Rental requests",
    questions: "Questions",

    dashboardTitle: "Owner dashboard",
    dashboardBody: "What needs your attention today.",
    statPendingRequests: "Pending requests",
    statUnanswered: "Unanswered questions",
    statPublished: "Live kos",
    statTotalListings: "Total kos",
    reviewRequests: "Review requests",
    answerQuestions: "Answer questions",
    manageListings: "Manage kos",
    allClear: "Nothing needs your attention.",

    sectionEarnings: "Earnings this month",
    sectionOccupancy: "Occupancy",
    sectionDemand: "Requests this month",
    sectionTasks: "Needs attention",
    earningsGross: "Gross earnings",
    earningsCommission: "Papikos commission",
    earningsNet: "Owner receives",
    earningsFrom: "from {count} approved requests",
    earningsNote:
      "Calculated from the requests you approved and the prices you set. Papikos never receives or holds money; payment stays directly between you and the renter.",
    occupancyRate: "Occupancy rate",
    occupancyRooms: "rooms occupied",
    occupancyFree: "Rooms free",
    demandTotal: "Total requests",
    demandApproved: "Approved",
    demandRejected: "Rejected",
    approvalRate: "Approval rate",
    noDecisions: "Nothing decided yet",
    fullyBookedAlert: "kos fully booked",

    listingsTitle: "My kos",
    listingsBody:
      "Choose which kos renters can see. Detail editing arrives with the API.",
    published: "Live",
    unpublished: "Hidden",
    suspended: "Suspended by admin",
    publish: "Publish",
    unpublish: "Hide",
    roomsAvailable: "rooms available",
    fullyBooked: "Full",
    publishedToast: "Kos published.",
    unpublishedToast: "Kos hidden from search.",
    suspendedHint: "Only an administrator can lift a suspension.",
    edit: "Edit",

    editTitle: "Edit kos details",
    editBody: "Changes appear to renters immediately.",
    basics: "Basics",
    fieldName: "Kos name",
    fieldDistrict: "District",
    fieldType: "Kos type",
    fieldDescription: "Description",
    fieldPrice: "Monthly price",
    fieldPromo: "Promo price",
    promoHint: "Leave empty when there is no discount.",
    promoInvalid: "The promo price must be lower than the normal price.",
    roomsSection: "Rooms",
    roomPrice: "Price",
    roomAvailable: "Rooms free",
    photosSection: "Kos photos",
    photosBody:
      "The first photo is used as the cover. Up to {max} photos; images are downscaled automatically so they fit in browser storage.",
    photosAdd: "Add photos",
    photosEmpty: "No photos yet. This kos uses the generated artwork.",
    photosCount: "{count} of {max} photos · {size}",
    photoCover: "Cover",
    photoMakeCover: "Make cover",
    photoRemove: "Remove photo",
    photoErrorType: "Only image files can be uploaded.",
    photoErrorCap: "The {max} photo limit was reached; the rest were skipped.",
    photoErrorRead: "That image could not be read. Try another file.",
    photoErrorQuota:
      "Browser storage is full. Remove some photos and save again.",
    photosUploading: "Processing photos…",
    amenitiesSection: "Amenities",
    rulesSection: "House rules",
    ruleAllowed: "Allowed",
    rulesStandard: "Standard rules",
    rulesCustom: "Additional rules",
    rulesCustomBody:
      "The standard rules still apply. Add rules specific to your kos here.",
    ruleNewPlaceholder: "For example: Guests must leave by 9pm",
    ruleAdd: "Add rule",
    ruleDelete: "Remove rule",
    ruleAllowedToggle: "Allowed",
    ruleForbiddenToggle: "Not allowed",
    ruleEmptyError: "Write the rule first.",
    costsSection: "Cost breakdown",
    costIncluded: "Included in rent",
    costAmount: "Amount",
    save: "Save changes",
    saved: "Changes saved.",
    reset: "Restore original data",
    resetDone: "Changes reverted.",
    edited: "Edited by owner",
    backToListings: "Back to kos list",

    requestsTitle: "Incoming rental requests",
    requestsBody:
      "Approve or reject renter requests. No payment is processed.",
    requestsEmpty: "No rental requests yet.",
    approve: "Approve",
    reject: "Reject",
    approvedToast: "Request approved.",
    rejectedToast: "Request rejected.",
    filterAll: "All",
    decidedAlready: "Already decided",

    questionsTitle: "Renter questions",
    questionsBody:
      "Answer asynchronously. Sent answers appear on the kos page.",
    questionsEmpty: "No renter questions yet.",
    answerPlaceholder: "Write an answer for the renter…",
    sendAnswer: "Send answer",
    answeredToast: "Answer sent.",
    yourAnswer: "Your answer",
    askedOn: "Asked",
  },
} as const;
