import type { AuthErrorCode } from "./auth-utils";

export const authCopy = {
  id: {
    loginTitle: "Masuk ke Papikos",
    loginSubtitle: "Lanjutkan pencarian kos dan simpan favoritmu.",
    registerTitle: "Buat akun Papikos",
    registerSubtitle: "Daftar untuk menyimpan favorit dan mengajukan sewa.",
    nameLabel: "Nama lengkap",
    namePlaceholder: "Nama sesuai identitas",
    emailLabel: "Email",
    emailPlaceholder: "nama@email.com",
    phoneLabel: "Nomor HP",
    phonePlaceholder: "08xxxxxxxxxx",
    passwordLabel: "Kata sandi",
    passwordPlaceholder: "Minimal 8 karakter",
    confirmPasswordLabel: "Ulangi kata sandi",
    showPassword: "Tampilkan kata sandi",
    hidePassword: "Sembunyikan kata sandi",
    roleLabel: "Saya ingin",
    roleRenter: "Mencari kos",
    roleOwner: "Menyewakan kos",
    termsLabel: "Saya setuju dengan ketentuan dan kebijakan privasi Papikos.",
    forgotPassword: "Lupa kata sandi?",
    loginSubmit: "Masuk",
    registerSubmit: "Daftar",
    noAccount: "Belum punya akun?",
    haveAccount: "Sudah punya akun?",
    goRegister: "Daftar sekarang",
    goLogin: "Masuk di sini",
    prototypeNotice:
      "Prototipe: autentikasi belum tersambung. Data yang kamu isi tidak dikirim atau disimpan di mana pun.",
    loginDoneTitle: "Form masuk tervalidasi",
    loginDoneBody:
      "Autentikasi asli akan hadir bersama API. Tidak ada sesi yang dibuat dan kata sandi tidak disimpan.",
    registerDoneTitle: "Form pendaftaran tervalidasi",
    registerDoneBody:
      "Pembuatan akun akan hadir bersama API. Tidak ada akun yang dibuat dan kata sandi tidak disimpan.",
    errors: {
      required: "Wajib diisi.",
      email: "Format email belum benar.",
      passwordLength: "Kata sandi minimal 8 karakter.",
      passwordMatch: "Kata sandi tidak sama.",
      phone: "Nomor HP Indonesia belum valid.",
      terms: "Kamu perlu menyetujui ketentuan.",
    } satisfies Record<AuthErrorCode, string>,
  },
  en: {
    loginTitle: "Sign in to Papikos",
    loginSubtitle: "Pick up your kos search and keep your favorites.",
    registerTitle: "Create a Papikos account",
    registerSubtitle: "Sign up to save favorites and send rental requests.",
    nameLabel: "Full name",
    namePlaceholder: "Name as on your ID",
    emailLabel: "Email",
    emailPlaceholder: "name@email.com",
    phoneLabel: "Phone number",
    phonePlaceholder: "08xxxxxxxxxx",
    passwordLabel: "Password",
    passwordPlaceholder: "At least 8 characters",
    confirmPasswordLabel: "Repeat password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    roleLabel: "I want to",
    roleRenter: "Find a kos",
    roleOwner: "List a kos",
    termsLabel: "I agree to the Papikos terms and privacy policy.",
    forgotPassword: "Forgot password?",
    loginSubmit: "Sign in",
    registerSubmit: "Sign up",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    goRegister: "Create one",
    goLogin: "Sign in here",
    prototypeNotice:
      "Prototype: authentication is not connected. Nothing you type is sent or stored anywhere.",
    loginDoneTitle: "Sign-in form validated",
    loginDoneBody:
      "Real authentication arrives with the API. No session was created and no password was stored.",
    registerDoneTitle: "Sign-up form validated",
    registerDoneBody:
      "Account creation arrives with the API. No account was created and no password was stored.",
    errors: {
      required: "This field is required.",
      email: "That email format looks off.",
      passwordLength: "Use at least 8 characters.",
      passwordMatch: "Passwords do not match.",
      phone: "That is not a valid Indonesian number.",
      terms: "Please accept the terms to continue.",
    } satisfies Record<AuthErrorCode, string>,
  },
} as const;
