import type { Amenity, ListingType, ListingTypeFilter, Locale } from "./types";

export const copy = {
  id: {
    skip: "Lewati ke konten utama",
    login: "Masuk",
    heroTitleStart: "Temukan kos yang",
    heroTitleAccent: "pas dengan hidupmu.",
    heroBody: "Masukkan kota atau area untuk mulai menemukan kos yang tepat.",
    location: "Lokasi",
    locationPlaceholder: "Kota, area, atau nama kos",
    roomType: "Tipe kos",
    maxBudget: "Anggaran maksimum",
    search: "Cari kos",
    popular: "Lokasi populer",
    popularBody: "Jelajahi kos dari kota yang paling sering dicari.",
    allLocations: "Semua",
    featuredEyebrow: "Pilihan untukmu",
    featured: "Kos yang layak dilihat",
    featuredBody:
      "Data contoh untuk menjelajahi pengalaman pencarian Papikos.",
    results: "hasil",
    verified: "Terverifikasi",
    roomsLeft: "kamar tersedia",
    perMonth: "per bulan",
    viewDetail: "Lihat detail",
    favoriteAdd: "Simpan ke favorit",
    favoriteRemove: "Hapus dari favorit",
    emptyTitle: "Belum ada kos yang cocok",
    emptyBody: "Coba perluas lokasi atau naikkan batas anggaranmu.",
    reset: "Atur ulang pencarian",
    surveyEyebrow: "Tidak yakin mulai dari mana?",
    surveyTitle: "Jawab 4 pertanyaan, dapatkan pilihan yang lebih personal.",
    surveyBody:
      "Papikos menghitung kecocokan dari kebutuhan yang kamu pilih—tanpa profil tersembunyi.",
    surveyCta: "Coba survei preferensi",
    surveyDialogTitle: "Ceritakan kos idealmu",
    surveyDialogBody: "Kami akan menunjukkan tiga kecocokan teratas beserta alasannya.",
    city: "Kota pilihan",
    desiredAmenities: "Fasilitas yang penting",
    showMatches: "Tampilkan kecocokan",
    close: "Tutup",
    match: "cocok",
    yourMatches: "Rekomendasi dari preferensimu",
    matchBudget: "Sesuai anggaran",
    matchLocation: "Lokasi pilihan",
    matchRoomType: "Tipe kos cocok",
    matchAmenities: "fasilitas terpenuhi",
    howEyebrow: "Sederhana dan transparan",
    howTitle: "Dari mencari sampai mengajukan sewa",
    howSteps: [
      {
        title: "Ceritakan kebutuhanmu",
        body: "Cari langsung atau isi survei singkat untuk menyusun prioritas.",
      },
      {
        title: "Bandingkan dengan jelas",
        body: "Lihat harga, fasilitas, ketersediaan, dan alasan kecocokan.",
      },
      {
        title: "Ajukan saat sudah yakin",
        body: "Kirim permintaan sewa kepada pemilik tanpa pembayaran di muka.",
      },
    ],
    footerTagline: "Cara lebih tenang untuk menemukan tempat tinggal berikutnya.",
    footerExplore: "Jelajahi",
    footerCompany: "Papikos",
    footerHelp: "Bantuan",
    footerLinks: {
      search: "Cari kos",
      survey: "Survei preferensi",
      about: "Tentang kami",
      privacy: "Privasi",
      terms: "Ketentuan",
      help: "Pusat bantuan",
      contact: "Kontak",
    },
    prototypeNotice: "Fitur ini akan hadir pada prototipe berikutnya.",
    searchUpdated: "Hasil pencarian diperbarui.",
    saved: "Kos disimpan ke favorit.",
    removed: "Kos dihapus dari favorit.",
    language: "Bahasa",
  },
  en: {
    skip: "Skip to main content",
    login: "Sign in",
    heroTitleStart: "Find a kos that",
    heroTitleAccent: "fits your life.",
    heroBody: "Enter a city or area to start finding the right kos.",
    location: "Location",
    locationPlaceholder: "City, area, or property name",
    roomType: "Kos type",
    maxBudget: "Maximum budget",
    search: "Find a kos",
    popular: "Popular locations",
    popularBody: "Explore kos in the cities people search most often.",
    allLocations: "All",
    featuredEyebrow: "Curated for you",
    featured: "Kos worth a closer look",
    featuredBody: "Sample data for exploring the Papikos search experience.",
    results: "results",
    verified: "Verified",
    roomsLeft: "rooms available",
    perMonth: "monthly",
    viewDetail: "View details",
    favoriteAdd: "Save to favorites",
    favoriteRemove: "Remove from favorites",
    emptyTitle: "No matching kos yet",
    emptyBody: "Try a wider location or increase your maximum budget.",
    reset: "Reset search",
    surveyEyebrow: "Not sure where to start?",
    surveyTitle: "Answer 4 questions for a more personal shortlist.",
    surveyBody:
      "Papikos calculates matches from the needs you choose—without hidden profiling.",
    surveyCta: "Try the preference survey",
    surveyDialogTitle: "Tell us about your ideal kos",
    surveyDialogBody: "We will show your top three matches and explain why.",
    city: "Preferred city",
    desiredAmenities: "Important amenities",
    showMatches: "Show my matches",
    close: "Close",
    match: "match",
    yourMatches: "Recommendations from your preferences",
    matchBudget: "Within budget",
    matchLocation: "Preferred location",
    matchRoomType: "Kos type matches",
    matchAmenities: "amenities matched",
    howEyebrow: "Simple and transparent",
    howTitle: "From search to rental request",
    howSteps: [
      {
        title: "Share what you need",
        body: "Search directly or take a short survey to set your priorities.",
      },
      {
        title: "Compare clearly",
        body: "See price, amenities, availability, and why each kos matches.",
      },
      {
        title: "Request when ready",
        body: "Send a rental request to the owner without paying upfront.",
      },
    ],
    footerTagline: "A calmer way to find your next place to live.",
    footerExplore: "Explore",
    footerCompany: "Papikos",
    footerHelp: "Help",
    footerLinks: {
      search: "Find a kos",
      survey: "Preference survey",
      about: "About us",
      privacy: "Privacy",
      terms: "Terms",
      help: "Help center",
      contact: "Contact",
    },
    prototypeNotice: "This feature is coming in the next prototype.",
    searchUpdated: "Search results updated.",
    saved: "Kos saved to favorites.",
    removed: "Kos removed from favorites.",
    language: "Language",
  },
} as const;

export const typeLabels: Record<Locale, Record<ListingTypeFilter, string>> = {
  id: {
    all: "Semua tipe",
    putra: "Putra",
    putri: "Putri",
    campur: "Campur",
  },
  en: {
    all: "All types",
    putra: "Men only",
    putri: "Women only",
    campur: "Mixed",
  },
};

export const amenityLabels: Record<Locale, Record<Amenity, string>> = {
  id: {
    wifi: "Wi-Fi",
    ac: "AC",
    privateBathroom: "Kamar mandi dalam",
    motorParking: "Parkir motor",
    kitchen: "Dapur",
    laundry: "Laundry",
  },
  en: {
    wifi: "Wi-Fi",
    ac: "Air conditioning",
    privateBathroom: "Private bathroom",
    motorParking: "Motorbike parking",
    kitchen: "Kitchen",
    laundry: "Laundry",
  },
};

export const shortTypeLabels: Record<Locale, Record<ListingType, string>> = {
  id: {
    putra: "Kos putra",
    putri: "Kos putri",
    campur: "Kos campur",
  },
  en: {
    putra: "Men-only kos",
    putri: "Women-only kos",
    campur: "Mixed kos",
  },
};
