import type { Amenity, ListingType, ListingTypeFilter, Locale } from "./types";

export const copy = {
  id: {
    skip: "Lewati ke konten utama",
    login: "Masuk",
    favorites: "Kos favorit",
    myRequests: "Permintaan sewa",
    heroTitleStart: "Temukan kos yang",
    heroTitleAccent: "pas dengan hidupmu.",
    location: "Lokasi",
    roomType: "Tipe kos",
    maxBudget: "Budget maksimum",
    locationPlaceholder: "Kota, area, atau nama kos",
    search: "Cari kos",
    exploreAllCta: "Lihat semua kos",
    featured: "Kos yang tersedia",
    featuredBody:
      "Data contoh untuk menjelajahi pengalaman pencarian Papikos.",
    results: "hasil",
    verified: "Terverifikasi",
    roomsLeft: "kamar tersedia",
    perMonth: "per bulan",
    viewDetail: "Lihat detail",
    favoriteAdd: "Simpan ke favorit",
    favoriteRemove: "Hapus dari favorit",
    emptyTitle: "Belum ada kos yang cocok",
    emptyBody: "Coba perluas lokasi atau naikkan batas anggaranmu.",
    reset: "Atur ulang pencarian",
    close: "Tutup",
    howTitle: "Dari mencari sampai mengajukan sewa",
    howSteps: [
      {
        title: "Ceritakan kebutuhanmu",
        body: "Cari langsung atau isi survei singkat untuk menyusun prioritas.",
      },
      {
        title: "Bandingkan dengan jelas",
        body: "Lihat harga, fasilitas, ketersediaan, dan alasan kecocokan.",
      },
      {
        title: "Ajukan saat sudah yakin",
        body: "Kirim permintaan sewa kepada pemilik tanpa pembayaran di muka.",
      },
    ],
    footerTagline: "Cara lebih tenang untuk menemukan tempat tinggal berikutnya.",
    footerExplore: "Jelajahi",
    footerCompany: "Papikos",
    footerHelp: "Bantuan",
    footerLinks: {
      search: "Cari kos",
      about: "Tentang kami",
      privacy: "Privasi",
      terms: "Ketentuan",
      help: "Pusat bantuan",
      contact: "Kontak",
    },
    prototypeNotice: "Fitur ini akan hadir pada prototipe berikutnya.",
    searchUpdated: "Hasil pencarian diperbarui.",
    saved: "Kos disimpan ke favorit.",
    removed: "Kos dihapus dari favorit.",
    language: "Bahasa",
  },
  en: {
    skip: "Skip to main content",
    login: "Sign in",
    favorites: "Saved kos",
    myRequests: "Rental requests",
    heroTitleStart: "Find a kos that",
    heroTitleAccent: "fits your life.",
    location: "Location",
    roomType: "Kos type",
    maxBudget: "Maximum budget",
    locationPlaceholder: "City, area, or property name",
    search: "Find a kos",
    exploreAllCta: "See all kos",
    featured: "Kos available now",
    featuredBody: "Nine sample kos across four cities.",
    results: "results",
    verified: "Verified",
    roomsLeft: "rooms available",
    perMonth: "monthly",
    viewDetail: "View details",
    favoriteAdd: "Save to favorites",
    favoriteRemove: "Remove from favorites",
    emptyTitle: "No matching kos yet",
    emptyBody: "Try a wider location or increase your maximum budget.",
    reset: "Reset search",
    close: "Close",
    howTitle: "From search to rental request",
    howSteps: [
      {
        title: "Share what you need",
        body: "Search by city, budget, room type, and the facilities you need.",
      },
      {
        title: "Compare clearly",
        body: "See price, amenities, and availability side by side before you decide.",
      },
      {
        title: "Request when ready",
        body: "Send a rental request to the owner without paying upfront.",
      },
    ],
    footerTagline: "A calmer way to find your next place to live.",
    footerExplore: "Explore",
    footerCompany: "Papikos",
    footerHelp: "Help",
    footerLinks: {
      search: "Find a kos",
      about: "About us",
      privacy: "Privacy",
      terms: "Terms",
      help: "Help center",
      contact: "Contact",
    },
    prototypeNotice: "This feature is coming in the next prototype.",
    searchUpdated: "Search results updated.",
    saved: "Kos saved to favorites.",
    removed: "Kos removed from favorites.",
    language: "Language",
  },
} as const;

export const typeLabels: Record<Locale, Record<ListingTypeFilter, string>> = {
  id: {
    all: "Semua",
    putra: "Putra",
    putri: "Putri",
    campur: "Campur",
  },
  en: {
    all: "All",
    putra: "Men only",
    putri: "Women only",
    campur: "Mixed",
  },
};

export const amenityLabels: Record<Locale, Record<Amenity, string>> = {
  id: {
    ac: "AC",
    privateBathroom: "Kamar mandi dalam",
    waterHeater: "Pemanas air",
    wardrobe: "Lemari",
    desk: "Meja belajar",
    tv: "TV",
    balcony: "Balkon",
    kitchen: "Dapur",
    livingRoom: "Ruang tamu",
    dryingArea: "Area jemur",
    prayerRoom: "Musala",
    fridge: "Kulkas",
    wifi: "Wi-Fi",
    laundry: "Laundry",
    cleaning: "Layanan kebersihan",
    dispenser: "Dispenser",
    cctv: "CCTV",
    securityGuard: "Penjaga kos",
    access24: "Akses 24 jam",
    keycard: "Akses kartu",
    motorParking: "Parkir motor",
    carParking: "Parkir mobil",
  },
  en: {
    ac: "Air conditioning",
    privateBathroom: "Private bathroom",
    waterHeater: "Water heater",
    wardrobe: "Wardrobe",
    desk: "Study desk",
    tv: "TV",
    balcony: "Balcony",
    kitchen: "Kitchen",
    livingRoom: "Living room",
    dryingArea: "Drying area",
    prayerRoom: "Prayer room",
    fridge: "Fridge",
    wifi: "Wi-Fi",
    laundry: "Laundry",
    cleaning: "Cleaning service",
    dispenser: "Water dispenser",
    cctv: "CCTV",
    securityGuard: "Caretaker",
    access24: "24-hour access",
    keycard: "Keycard entry",
    motorParking: "Motorbike parking",
    carParking: "Car parking",
  },
};

export const shortTypeLabels: Record<Locale, Record<ListingType, string>> = {
  id: {
    putra: "Kos putra",
    putri: "Kos putri",
    campur: "Kos campur",
  },
  en: {
    putra: "Men-only kos",
    putri: "Women-only kos",
    campur: "Mixed kos",
  },
};
