import type { Amenity, Listing } from "./types";

export const cities = ["Jakarta", "Bandung", "Yogyakarta", "Surabaya"];

export const amenities: Amenity[] = [
  "wifi",
  "ac",
  "privateBathroom",
  "motorParking",
  "kitchen",
  "laundry",
];

export const listings: Listing[] = [
  {
    id: "senja-setiabudi",
    name: "Papikos Senja Setiabudi",
    city: "Jakarta",
    district: "Setiabudi",
    type: "campur",
    price: 2450000,
    amenities: ["wifi", "ac", "privateBathroom", "laundry"],
    availableRooms: 2,
    verified: true,
    tone: "from-blue-700 via-blue-600 to-cyan-500",
    accent: "bg-cyan-200",
  },
  {
    id: "asri-dago",
    name: "Kos Asri Dago",
    city: "Bandung",
    district: "Coblong",
    type: "putri",
    price: 1650000,
    amenities: ["wifi", "privateBathroom", "motorParking", "kitchen"],
    availableRooms: 3,
    verified: true,
    tone: "from-indigo-700 via-blue-600 to-sky-400",
    accent: "bg-amber-200",
  },
  {
    id: "kalyana-gejayan",
    name: "Kalyana Living Gejayan",
    city: "Yogyakarta",
    district: "Depok",
    type: "putri",
    price: 1350000,
    amenities: ["wifi", "ac", "privateBathroom", "motorParking"],
    availableRooms: 1,
    verified: true,
    tone: "from-sky-700 via-cyan-600 to-teal-400",
    accent: "bg-rose-200",
  },
  {
    id: "ruang-teduh",
    name: "Ruang Teduh Keputih",
    city: "Surabaya",
    district: "Sukolilo",
    type: "putra",
    price: 1200000,
    amenities: ["wifi", "motorParking", "kitchen"],
    availableRooms: 4,
    verified: false,
    tone: "from-slate-700 via-blue-700 to-blue-400",
    accent: "bg-lime-200",
  },
  {
    id: "nara-kemang",
    name: "Nara House Kemang",
    city: "Jakarta",
    district: "Mampang Prapatan",
    type: "campur",
    price: 2850000,
    amenities: ["wifi", "ac", "privateBathroom", "motorParking", "kitchen"],
    availableRooms: 2,
    verified: true,
    tone: "from-blue-950 via-indigo-800 to-blue-500",
    accent: "bg-violet-200",
  },
  {
    id: "bumi-pasteur",
    name: "Bumi Pasteur Residence",
    city: "Bandung",
    district: "Sukajadi",
    type: "putra",
    price: 1850000,
    amenities: ["wifi", "ac", "motorParking", "laundry"],
    availableRooms: 5,
    verified: true,
    tone: "from-cyan-800 via-sky-600 to-blue-400",
    accent: "bg-orange-200",
  },
  {
    id: "oma-pogung",
    name: "Omah Pogung Ceria",
    city: "Yogyakarta",
    district: "Mlati",
    type: "campur",
    price: 950000,
    amenities: ["wifi", "motorParking", "kitchen", "laundry"],
    availableRooms: 3,
    verified: false,
    tone: "from-blue-800 via-cyan-700 to-emerald-400",
    accent: "bg-sky-200",
  },
  {
    id: "taman-rungkut",
    name: "Taman Rungkut Putri",
    city: "Surabaya",
    district: "Rungkut",
    type: "putri",
    price: 1550000,
    amenities: ["wifi", "ac", "privateBathroom", "kitchen", "laundry"],
    availableRooms: 2,
    verified: true,
    tone: "from-indigo-900 via-blue-700 to-cyan-400",
    accent: "bg-fuchsia-200",
  },
];
