export const accountCopy = {
  id: {
    favoritesTitle: "Kos favorit",
    favoritesBody: "Kos yang kamu simpan tersedia di perangkat ini.",
    favoritesEmptyTitle: "Belum ada kos favorit",
    favoritesEmptyBody:
      "Tekan ikon hati pada kos yang menarik untuk menyimpannya di sini.",
    favoritesEmptyCta: "Cari kos",
    savedCount: "kos disimpan",

    requestsTitle: "Permintaan sewa",
    requestsBody: "Pantau status pengajuan sewamu di sini.",
    requestsEmptyTitle: "Belum ada permintaan sewa",
    requestsEmptyBody:
      "Ajukan sewa dari halaman detail kos untuk melihat statusnya di sini.",
    requestsEmptyCta: "Cari kos",
    submittedOn: "Diajukan",
    moveIn: "Mulai masuk",
    duration: "Durasi",
    months: "bulan",
    room: "Kamar",
    note: "Catatan",
    history: "Riwayat status",
    cancel: "Batalkan permintaan",
    cancelled: "Permintaan dibatalkan.",
    viewListing: "Lihat kos",
    byRenter: "oleh penyewa",
    byOwner: "oleh pemilik",
    byAdmin: "oleh admin",
  },
  en: {
    favoritesTitle: "Saved kos",
    favoritesBody: "The kos you saved on this device.",
    favoritesEmptyTitle: "No saved kos yet",
    favoritesEmptyBody:
      "Tap the heart on any kos you like to keep it here.",
    favoritesEmptyCta: "Find a kos",
    savedCount: "kos saved",

    requestsTitle: "Rental requests",
    requestsBody: "Track the status of the requests you have sent.",
    requestsEmptyTitle: "No rental requests yet",
    requestsEmptyBody:
      "Send a request from a kos detail page to track it here.",
    requestsEmptyCta: "Find a kos",
    submittedOn: "Submitted",
    moveIn: "Move-in",
    duration: "Duration",
    months: "months",
    room: "Room",
    note: "Note",
    history: "Status history",
    cancel: "Cancel request",
    cancelled: "Request cancelled.",
    viewListing: "View kos",
    byRenter: "by renter",
    byOwner: "by owner",
    byAdmin: "by admin",
  },
} as const;
