-- Basic account table for the Papikos backend.
-- Passwords are stored as salted hashes generated by the backend, never as plain text.

begin;

create type user_role as enum ('pencari-kos', 'pemilik-kos');

create table users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone_number text not null unique,
  email text not null unique,
  password_hash text not null,
  password_salt text not null,
  role user_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index users_role_idx on users (role);
create index users_email_idx on users (email);
create index users_phone_number_idx on users (phone_number);

commit;
