-- Persistent renter workflows attached to authenticated users and kos listings.

begin;

create table survey_requests (
  id bigint generated by default as identity primary key,
  renter_id bigint not null references users(id) on delete cascade,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  scheduled_for timestamptz not null,
  notes text not null default '',
  status text not null default 'pending'
    check (status in ('pending', 'confirmed', 'completed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table contact_requests (
  id bigint generated by default as identity primary key,
  renter_id bigint not null references users(id) on delete cascade,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  message text not null default '',
  status text not null default 'open'
    check (status in ('open', 'answered', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table rental_applications (
  id bigint generated by default as identity primary key,
  renter_id bigint not null references users(id) on delete cascade,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  rental_months integer not null check (rental_months > 0),
  payment_method text not null check (payment_method in ('full', 'dp')),
  quoted_total integer not null check (quoted_total >= 0),
  quote_snapshot jsonb not null,
  status text not null default 'submitted'
    check (status in ('submitted', 'reviewing', 'accepted', 'rejected', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index survey_requests_renter_idx on survey_requests (renter_id, created_at desc);
create index survey_requests_kos_idx on survey_requests (kos_id, scheduled_for);
create index contact_requests_renter_idx on contact_requests (renter_id, created_at desc);
create index contact_requests_kos_idx on contact_requests (kos_id, created_at desc);
create index rental_applications_renter_idx on rental_applications (renter_id, created_at desc);
create index rental_applications_kos_idx on rental_applications (kos_id, created_at desc);

commit;
