-- Normalize repeated facility data into global catalogs and per-kos assignments.
-- Compatibility views retain the legacy names used by both backend implementations.

begin;

create table facility_categories (
  id text primary key,
  title text not null unique,
  sort_order integer not null default 0
);

create table facility_catalog (
  id bigint generated by default as identity primary key,
  category_id text not null references facility_categories(id) on delete restrict,
  name text not null unique
);

create table kos_facility_assignments (
  kos_id bigint not null references kos_listings(id) on delete cascade,
  facility_id bigint not null references facility_catalog(id) on delete restrict,
  is_highlighted boolean not null default false,
  sort_order integer not null default 0,
  highlight_sort_order integer,
  constraint facility_highlight_order_complete check (
    (is_highlighted and highlight_sort_order is not null)
    or (not is_highlighted and highlight_sort_order is null)
  ),
  primary key (kos_id, facility_id)
);

create table rule_catalog (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table kos_rule_assignments (
  kos_id bigint not null references kos_listings(id) on delete cascade,
  rule_id bigint not null references rule_catalog(id) on delete restrict,
  sort_order integer not null default 0,
  primary key (kos_id, rule_id)
);

create index facility_catalog_category_idx on facility_catalog (category_id, name);
create index kos_facility_assignments_facility_idx
  on kos_facility_assignments (facility_id, kos_id);
create index kos_facility_assignments_highlighted_idx
  on kos_facility_assignments (kos_id, highlight_sort_order)
  where is_highlighted;
create index facility_catalog_name_lower_idx on facility_catalog (lower(name));
create index kos_rule_assignments_rule_idx on kos_rule_assignments (rule_id, kos_id);

-- Copy the existing per-listing categories into one shared category catalog.
insert into facility_categories (id, title, sort_order)
select id, min(title), min(sort_order)
from kos_facility_categories
group by id;

insert into facility_categories (id, title, sort_order)
select 'lainnya', 'Fasilitas lainnya', 999
where exists (
  select 1
  from kos_facilities highlight
  where not exists (
    select 1
    from kos_facility_category_items item
    where item.name = highlight.name
  )
)
on conflict (id) do nothing;

-- A facility name represents one concept, stored once and assigned to many kos.
insert into facility_catalog (category_id, name)
select distinct on (name) category_id, name
from kos_facility_category_items
order by name, category_id;

insert into kos_facility_assignments (
  kos_id,
  facility_id,
  is_highlighted,
  sort_order,
  highlight_sort_order
)
select
  item.kos_id,
  facility.id,
  exists (
    select 1
    from kos_facilities highlight
    where highlight.kos_id = item.kos_id
      and highlight.name = item.name
  ),
  item.sort_order,
  (
    select highlight.sort_order
    from kos_facilities highlight
    where highlight.kos_id = item.kos_id
      and highlight.name = item.name
  )
from kos_facility_category_items item
join facility_catalog facility on facility.name = item.name
on conflict (kos_id, facility_id) do update
set
  is_highlighted = excluded.is_highlighted,
  sort_order = excluded.sort_order,
  highlight_sort_order = excluded.highlight_sort_order;

-- Preserve any highlighted legacy facility that was not categorized.
insert into facility_catalog (category_id, name)
select 'lainnya', highlight.name
from kos_facilities highlight
where not exists (
  select 1 from facility_catalog facility where facility.name = highlight.name
)
group by highlight.name
on conflict (name) do nothing;

insert into kos_facility_assignments (
  kos_id,
  facility_id,
  is_highlighted,
  sort_order,
  highlight_sort_order
)
select highlight.kos_id, facility.id, true, highlight.sort_order, highlight.sort_order
from kos_facilities highlight
join facility_catalog facility on facility.name = highlight.name
on conflict (kos_id, facility_id) do update
set
  is_highlighted = true,
  highlight_sort_order = excluded.highlight_sort_order;

insert into rule_catalog (name)
select distinct rule from kos_rules
on conflict (name) do nothing;

insert into kos_rule_assignments (kos_id, rule_id, sort_order)
select legacy.kos_id, catalog.id, legacy.sort_order
from kos_rules legacy
join rule_catalog catalog on catalog.name = legacy.rule
on conflict (kos_id, rule_id) do update
set sort_order = excluded.sort_order;

drop table kos_facility_category_items;
drop table kos_facility_categories;
drop table kos_facilities;
drop table kos_rules;

-- Read-compatible views allow the current Node repository and backend-dev's
-- FastAPI SELECT queries to use the old names during the eventual merge.
create view kos_facility_categories as
select
  assignment.kos_id,
  category.id,
  category.title,
  category.sort_order
from kos_facility_assignments assignment
join facility_catalog facility on facility.id = assignment.facility_id
join facility_categories category on category.id = facility.category_id
group by assignment.kos_id, category.id, category.title, category.sort_order;

create view kos_facility_category_items as
select
  facility.id,
  assignment.kos_id,
  facility.category_id,
  facility.name,
  assignment.sort_order
from kos_facility_assignments assignment
join facility_catalog facility on facility.id = assignment.facility_id;

create view kos_facilities as
select
  facility.id,
  assignment.kos_id,
  facility.name,
  assignment.highlight_sort_order as sort_order
from kos_facility_assignments assignment
join facility_catalog facility on facility.id = assignment.facility_id
where assignment.is_highlighted;

create view kos_rules as
select
  catalog.id,
  assignment.kos_id,
  catalog.name as rule,
  assignment.sort_order
from kos_rule_assignments assignment
join rule_catalog catalog on catalog.id = assignment.rule_id;

-- Remove indexes duplicated by existing UNIQUE constraints. The expression
-- index remains the authoritative location uniqueness rule for NULL parents.
alter table admin_locations
  drop constraint if exists admin_locations_type_name_parent_id_key;
drop index if exists users_email_idx;
drop index if exists users_phone_number_idx;

create index kos_listings_filter_idx
  on kos_listings (tag, monthly_price)
  include (available_rooms);

commit;
