-- Owner-defined listing details and a renter account for the unified demo login.

begin;

create table kos_custom_facilities (
  id bigint generated by default as identity primary key,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  category text not null default 'Fasilitas lainnya',
  name text not null,
  sort_order integer not null default 0,
  constraint kos_custom_facility_name_not_blank check (btrim(name) <> ''),
  constraint kos_custom_facility_category_not_blank check (btrim(category) <> '')
);

create unique index kos_custom_facilities_name_idx
  on kos_custom_facilities (kos_id, lower(name));

create table kos_custom_rules (
  id bigint generated by default as identity primary key,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  constraint kos_custom_rule_name_not_blank check (btrim(name) <> '')
);

create unique index kos_custom_rules_name_idx
  on kos_custom_rules (kos_id, lower(name));

create index kos_custom_facilities_listing_idx
  on kos_custom_facilities (kos_id, sort_order);

create index kos_custom_rules_listing_idx
  on kos_custom_rules (kos_id, sort_order);

insert into users (
  full_name,
  phone_number,
  email,
  password_hash,
  password_salt,
  role,
  is_active,
  verification_status
) values (
  'Pencari Kos Demo',
  '083333333333',
  'pencari@papikos.local',
  'c34752eb13594c85d2df49d8bce767ba72488ca88ebaab3e3679a5a65bbc451e1c26be0e17b72664b307a883ef47a664b65faff3ccee7c1f43cd53de689c9e9c',
  'papikos-renter-demo-2026',
  'pencari-kos',
  true,
  'not_required'
)
on conflict (phone_number) do update
set
  full_name = excluded.full_name,
  email = excluded.email,
  password_hash = excluded.password_hash,
  password_salt = excluded.password_salt,
  role = excluded.role,
  is_active = excluded.is_active,
  verification_status = excluded.verification_status,
  updated_at = now();

commit;
