export const detailCopy = {
  id: {
    skip: "Lewati ke konten utama",
    login: "Masuk",
    language: "Bahasa",
    verified: "Terverifikasi",
    unverified: "Belum diverifikasi",
    updated: "Diperbarui",
    favoriteAdd: "Simpan ke favorit",
    favoriteRemove: "Hapus dari favorit",
    share: "Bagikan",
    report: "Laporkan",
    perMonth: "per bulan",
    roomsAvailable: "Kamar tersedia",
    roomAvailabilityCount: "kamar tersedia",
    availableFrom: "Tersedia mulai",
    minimumStay: "Minimal sewa",
    month: "bulan",
    requestRental: "Ajukan sewa",
    startingFrom: "Mulai dari",
    prototypeLabel: "Prototipe lokal—tidak ada pembayaran",
    overview: "Ringkasan",
    rooms: "Pilihan kamar",
    roomsBody: "Bandingkan ruang, fasilitas, harga, dan ketersediaan setiap kamar.",
    unavailable: "Penuh",
    privateBathroom: "Kamar mandi dalam",
    sharedBathroom: "Kamar mandi bersama",
    costs: "Rincian biaya",
    costsBody: "Semua biaya yang diketahui ditampilkan sebelum kamu mengajukan sewa.",
    included: "Termasuk",
    noCharge: "Tanpa biaya",
    costUnstated: "Belum ditentukan",
    explainCost: "Lihat penjelasan biaya",
    costDialogTitle: "Penjelasan biaya",
    facilities: "Fasilitas",
    facilityGroups: {
      room: "Di dalam kamar",
      shared: "Area bersama",
      service: "Layanan",
      security: "Keamanan",
      parking: "Parkir",
    },
    location: "Lokasi dan sekitar",
    approximate: "Lokasi perkiraan",
    addressTitle: "Alamat lengkap",
    addressLocked:
      "Alamat lengkap dan petunjuk arah dikirim pemilik setelah permintaan sewamu disetujui.",
    addressUnlocked: "Permintaanmu disetujui, jadi pemilik membagikan ini:",
    privacy:
      "Lingkaran menandai area dalam radius {radius} m. Alamat persis tidak dibagikan sebelum permintaan sewa disetujui.",
    minutes: "menit",
    rules: "Peraturan kos",
    allowed: "Diizinkan",
    notAllowed: "Tidak diizinkan",
    owner: "Pemilik dan verifikasi",
    ownerSince: "Bergabung sejak",
    identityChecked: "Identitas pemilik diperiksa",
    propertyChecked: "Data properti diperiksa",
    checkedAt: "Pemeriksaan terakhir",
    notYetChecked: "Belum selesai diperiksa",
    questions: "Tanya jawab kos",
    questionsBody: "Pertanyaan tetap terhubung ke kos ini dan dijawab secara asinkron.",
    answered: "Dijawab pemilik",
    pending: "Menunggu jawaban",
    askLabel: "Pertanyaanmu",
    askPlaceholder: "Contoh: apakah tersedia meja tambahan?",
    askSubmit: "Kirim pertanyaan",
    askSuccess: "Pertanyaan tersimpan untuk pemilik (prototipe).",
    similar: "Kos serupa yang layak dibandingkan",
    similarReason: "Dekat dalam harga, lokasi, atau tipe kos",
    viewDetail: "Lihat detail",
    bookingTitle: "Ajukan permintaan sewa",
    bookingBody:
      "Pemilik akan meninjau permintaan ini. Kamu belum dikenai biaya apa pun.",
    roomChoice: "Pilihan kamar",
    moveIn: "Tanggal masuk",
    duration: "Durasi sewa",
    note: "Catatan untuk pemilik",
    notePlaceholder: "Perkenalkan kebutuhanmu secara singkat (opsional)",
    submitRequest: "Kirim permintaan",
    bookingSuccessTitle: "Permintaan sewa terkirim",
    bookingSuccessBody:
      "Statusnya pending dan tersimpan hanya di browser ini untuk keperluan prototipe.",
    close: "Tutup",
    galleryPrevious: "Foto sebelumnya",
    galleryNext: "Foto berikutnya",
    galleryOpen: "Lihat foto lebih besar",
    galleryGoTo: "Lihat foto ke-{index}",
    galleryCounter: "{index} dari {total}",
    galleryDialog: "Galeri foto",
    reportTitle: "Laporkan informasi kos",
    reportBody: "Bantu kami menandai data yang perlu diperiksa.",
    reportReason: "Bagian yang bermasalah",
    reportOptions: {
      price: "Harga atau biaya",
      availability: "Ketersediaan kamar",
      facilities: "Fasilitas",
      location: "Lokasi",
      other: "Lainnya",
    },
    reportDetails: "Detail laporan",
    reportPlaceholder: "Jelaskan informasi yang perlu diperiksa",
    submitReport: "Kirim laporan",
    reportSuccess: "Laporan tersimpan untuk antrean moderasi prototipe.",
    shared: "Tautan detail kos disalin.",
    shareFailed: "Tautan siap dibagikan.",
    saved: "Kos disimpan ke favorit.",
    removed: "Kos dihapus dari favorit.",
    footerTagline: "Cara lebih tenang untuk menemukan tempat tinggal berikutnya.",
  },
  en: {
    skip: "Skip to main content",
    login: "Sign in",
    language: "Language",
    verified: "Verified",
    unverified: "Not yet verified",
    updated: "Updated",
    favoriteAdd: "Save to favorites",
    favoriteRemove: "Remove from favorites",
    share: "Share",
    report: "Report",
    perMonth: "per month",
    roomsAvailable: "Rooms available",
    roomAvailabilityCount: "rooms available",
    availableFrom: "Available from",
    minimumStay: "Minimum stay",
    month: "months",
    requestRental: "Request to rent",
    startingFrom: "Starting from",
    prototypeLabel: "Local prototype—no payment",
    overview: "Overview",
    rooms: "Room options",
    roomsBody: "Compare the space, facilities, price, and availability of each room.",
    unavailable: "Unavailable",
    privateBathroom: "Private bathroom",
    sharedBathroom: "Shared bathroom",
    costs: "Cost breakdown",
    costsBody: "Every known cost is shown before you submit a rental request.",
    included: "Included",
    noCharge: "No charge",
    costUnstated: "Not stated",
    explainCost: "See how this charge works",
    costDialogTitle: "Cost explanation",
    facilities: "Facilities",
    facilityGroups: {
      room: "Inside the room",
      shared: "Shared areas",
      service: "Services",
      security: "Security",
      parking: "Parking",
    },
    location: "Location and surroundings",
    approximate: "Approximate location",
    addressTitle: "Full address",
    addressLocked:
      "The owner shares the full address and directions once your rental request is approved.",
    addressUnlocked: "Your request was approved, so the owner shared this:",
    privacy:
      "The circle covers a {radius} m radius. The exact address is not shared until a rental request is approved.",
    minutes: "minutes",
    rules: "House rules",
    allowed: "Allowed",
    notAllowed: "Not allowed",
    owner: "Owner and verification",
    ownerSince: "Member since",
    identityChecked: "Owner identity checked",
    propertyChecked: "Property information checked",
    checkedAt: "Last verification",
    notYetChecked: "Verification not complete",
    questions: "Listing Q&A",
    questionsBody: "Questions stay attached to this kos and are answered asynchronously.",
    answered: "Answered by owner",
    pending: "Awaiting answer",
    askLabel: "Your question",
    askPlaceholder: "Example: can an extra desk be provided?",
    askSubmit: "Submit question",
    askSuccess: "Question saved for the owner (prototype).",
    similar: "Similar kos worth comparing",
    similarReason: "Close in price, location, or kos type",
    viewDetail: "View details",
    bookingTitle: "Submit a rental request",
    bookingBody:
      "The owner will review this request. You will not be charged anything.",
    roomChoice: "Room choice",
    moveIn: "Move-in date",
    duration: "Rental duration",
    note: "Note for the owner",
    notePlaceholder: "Briefly introduce your needs (optional)",
    submitRequest: "Submit request",
    bookingSuccessTitle: "Rental request submitted",
    bookingSuccessBody:
      "Its status is pending and it is stored only in this browser for the prototype.",
    close: "Close",
    galleryPrevious: "Previous photo",
    galleryNext: "Next photo",
    galleryOpen: "View this photo larger",
    galleryGoTo: "Go to photo {index}",
    galleryCounter: "{index} of {total}",
    galleryDialog: "Photo gallery",
    reportTitle: "Report listing information",
    reportBody: "Help us flag information that should be checked.",
    reportReason: "What is inaccurate?",
    reportOptions: {
      price: "Price or costs",
      availability: "Room availability",
      facilities: "Facilities",
      location: "Location",
      other: "Other",
    },
    reportDetails: "Report details",
    reportPlaceholder: "Explain what information should be checked",
    submitReport: "Submit report",
    reportSuccess: "Report saved to the prototype moderation queue.",
    shared: "Listing link copied.",
    shareFailed: "The listing link is ready to share.",
    saved: "Kos saved to favorites.",
    removed: "Kos removed from favorites.",
    footerTagline: "A calmer way to find your next place to live.",
  },
} as const;
