export const adminCopy = {
  id: {
    area: "Area admin",
    overview: "Ringkasan",
    verification: "Verifikasi",
    reports: "Laporan",
    listings: "Kelola kos",
    audit: "Jejak audit",

    overviewTitle: "Ringkasan marketplace",
    overviewBody: "Angka dasar dari data prototipe di perangkat ini.",
    statListings: "Total kos",
    statLive: "Kos tayang",
    statVerified: "Kos terverifikasi",
    statRequests: "Total permintaan",
    statPendingRequests: "Permintaan menunggu",
    statOpenReports: "Laporan terbuka",
    statAveragePrice: "Rata-rata harga",
    byCity: "Sebaran kota",

    verificationTitle: "Verifikasi kos",
    verificationBody:
      "Tandai kos yang identitas pemilik dan propertinya sudah diperiksa.",
    verified: "Terverifikasi",
    unverified: "Belum diverifikasi",
    verify: "Verifikasi",
    unverify: "Cabut verifikasi",
    verifiedToast: "Kos diverifikasi.",
    unverifiedToast: "Verifikasi dicabut.",
    overridden: "Disetel admin",

    reportsTitle: "Laporan kos",
    reportsBody: "Tinjau laporan dari penyewa dan tutup setelah ditindak.",
    reportsEmpty: "Belum ada laporan masuk.",
    reportReason: "Alasan",
    markReviewing: "Tandai ditinjau",
    markResolved: "Selesaikan",
    markDismissed: "Tutup",
    reportUpdated: "Status laporan diperbarui.",

    listingsTitle: "Kelola kos",
    listingsBody:
      "Tangguhkan kos yang bermasalah. Kos yang ditangguhkan hilang dari pencarian.",
    publish: "Tayangkan",
    unpublish: "Sembunyikan",
    suspend: "Tangguhkan",
    unsuspend: "Cabut penangguhan",
    live: "Tayang",
    hidden: "Tidak tayang",
    suspended: "Ditangguhkan",
    suspendToast: "Kos ditangguhkan.",
    unsuspendToast: "Penangguhan dicabut.",

    auditTitle: "Jejak audit",
    auditBody:
      "Setiap perubahan istimewa tercatat lengkap dengan pelaku dan waktunya.",
    auditEmpty: "Belum ada aktivitas tercatat.",
    actor: "Pelaku",
    action: "Aksi",
    target: "Objek",
    when: "Waktu",
    clearLog: "Kosongkan jejak",
    logCleared: "Jejak audit dikosongkan.",
  },
  en: {
    area: "Admin area",
    overview: "Overview",
    verification: "Verification",
    reports: "Reports",
    listings: "Manage kos",
    audit: "Audit trail",

    overviewTitle: "Marketplace overview",
    overviewBody: "Basic figures from the prototype data on this device.",
    statListings: "Total kos",
    statLive: "Live kos",
    statVerified: "Verified kos",
    statRequests: "Total requests",
    statPendingRequests: "Pending requests",
    statOpenReports: "Open reports",
    statAveragePrice: "Average price",
    byCity: "City spread",

    verificationTitle: "Kos verification",
    verificationBody:
      "Mark the kos whose owner identity and property have been checked.",
    verified: "Verified",
    unverified: "Unverified",
    verify: "Verify",
    unverify: "Remove verification",
    verifiedToast: "Kos verified.",
    unverifiedToast: "Verification removed.",
    overridden: "Set by admin",

    reportsTitle: "Listing reports",
    reportsBody: "Review renter reports and close them once handled.",
    reportsEmpty: "No reports yet.",
    reportReason: "Reason",
    markReviewing: "Mark reviewing",
    markResolved: "Resolve",
    markDismissed: "Dismiss",
    reportUpdated: "Report status updated.",

    listingsTitle: "Manage kos",
    listingsBody:
      "Suspend problematic kos. A suspended kos disappears from search.",
    publish: "Publish",
    unpublish: "Hide",
    suspend: "Suspend",
    unsuspend: "Lift suspension",
    live: "Live",
    hidden: "Hidden",
    suspended: "Suspended",
    suspendToast: "Kos suspended.",
    unsuspendToast: "Suspension lifted.",

    auditTitle: "Audit trail",
    auditBody: "Every privileged change is recorded with its actor and time.",
    auditEmpty: "No recorded activity yet.",
    actor: "Actor",
    action: "Action",
    target: "Target",
    when: "When",
    clearLog: "Clear trail",
    logCleared: "Audit trail cleared.",
  },
} as const;
