-- Papikos PostgreSQL schema
-- This database belongs behind the backend API.
-- The React frontend should never connect directly to PostgreSQL.

begin;

create type kos_tag as enum ('Putra', 'Putri', 'Campur');
create type media_type as enum ('image', 'video');
create type rental_duration as enum ('Bulanan', '3 Bulan', '6 Bulan', 'Tahunan');
create type location_type as enum ('province', 'city', 'area', 'campus');

create table admin_locations (
  id bigint generated by default as identity primary key,
  name text not null,
  type location_type not null,
  parent_id bigint references admin_locations(id) on delete cascade,
  aliases text[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (type, name, parent_id)
);

create table kos_listings (
  id bigint generated by default as identity primary key,
  title text not null,
  city text not null,
  monthly_price integer not null check (monthly_price >= 0),
  rating numeric(2, 1) not null check (rating >= 0 and rating <= 5),
  tag kos_tag not null,
  address text not null,
  description text not null,
  room_size text not null,
  available_rooms integer not null default 0 check (available_rooms >= 0),
  owner_name text not null,
  image_url text not null,
  image_alt text not null,
  is_featured boolean not null default false,
  latitude numeric(10, 7),
  longitude numeric(10, 7),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint kos_coordinates_complete check (
    (latitude is null and longitude is null)
    or
    (latitude is not null and longitude is not null)
  )
);

create table kos_payment_terms (
  kos_id bigint primary key references kos_listings(id) on delete cascade,
  dp_percentage integer not null check (dp_percentage >= 0 and dp_percentage <= 100),
  service_fee integer not null default 0 check (service_fee >= 0),
  admin_fee integer not null default 0 check (admin_fee >= 0),
  deposit integer not null default 0 check (deposit >= 0),
  discount_percentage integer not null default 0 check (
    discount_percentage >= 0 and discount_percentage <= 100
  )
);

create table kos_facilities (
  id bigint generated by default as identity primary key,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  unique (kos_id, name)
);

create table kos_facility_categories (
  id text not null,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  title text not null,
  sort_order integer not null default 0,
  primary key (kos_id, id)
);

create table kos_facility_category_items (
  id bigint generated by default as identity primary key,
  kos_id bigint not null,
  category_id text not null,
  name text not null,
  sort_order integer not null default 0,
  foreign key (kos_id, category_id)
    references kos_facility_categories(kos_id, id)
    on delete cascade,
  unique (kos_id, category_id, name)
);

create table kos_rules (
  id bigint generated by default as identity primary key,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  rule text not null,
  sort_order integer not null default 0,
  unique (kos_id, rule)
);

create table kos_rental_durations (
  kos_id bigint not null references kos_listings(id) on delete cascade,
  duration rental_duration not null,
  sort_order integer not null default 0,
  primary key (kos_id, duration)
);

create table kos_media (
  id text not null,
  kos_id bigint not null references kos_listings(id) on delete cascade,
  category text not null,
  label text not null,
  type media_type not null,
  url text not null,
  thumbnail_url text,
  alt text not null,
  sort_order integer not null default 0,
  primary key (kos_id, id)
);

create table kos_nearby_campuses (
  kos_id bigint not null references kos_listings(id) on delete cascade,
  campus_name text not null,
  sort_order integer not null default 0,
  primary key (kos_id, campus_name)
);

create index admin_locations_name_idx on admin_locations using gin (to_tsvector('simple', name));
create unique index admin_locations_unique_idx
  on admin_locations (type, name, coalesce(parent_id, 0));
create index kos_listings_city_idx on kos_listings (city);
create index kos_listings_tag_idx on kos_listings (tag);
create index kos_listings_monthly_price_idx on kos_listings (monthly_price);
create index kos_listings_featured_idx on kos_listings (is_featured) where is_featured;
create index kos_listings_coordinates_idx on kos_listings (latitude, longitude)
  where latitude is not null and longitude is not null;
create index kos_facilities_name_idx on kos_facilities (name);
create index kos_nearby_campuses_name_idx on kos_nearby_campuses (campus_name);

commit;
